在项目设置页面添加了提交功能以及controller中添加了post()
OS-ABC/Kcoin-Golang pull request #244
Opened 2019-12-11 13:29 UTC by a5759567

2019-12-12 07:43 UTC, zhang2j requested changes
把controller中的project结构体放到models/models.go中吧

2019-12-12 15:51 UTC, a5759567 commented
@zhang2j 已修改

2019-12-14 01:43 UTC, zhang2j commented on src/controllers/projectSetting.go
> +	err =c.SaveToFile("Projectcover","static/"+filename)
这个项目封面不应该直接存放到static目录下吧，也许应该在static/img目录下新建一个文件夹来存放。

2019-12-14 06:39 UTC, a5759567 commented on src/controllers/projectSetting.go
> +	err =c.SaveToFile("Projectcover","static/"+filename)
好的

2019-12-17 02:10 UTC, a5759567 commented
issue #226

2020-03-21 11:14 UTC, closed without merging